import pytest

from collections import OrderedDict
from zone_iterator import split_comments, zone_iterator, zone_dict_to_str

REFERENCE_COM_ZONE = [OrderedDict([('origin', 'com.'),
                                   ('ttl', '900'),
                                   ('class', 'in'),
                                   ('type', 'soa'),
                                   ('data', ['a.gtld-servers.net.',
                                             'nstld.verisign-grs.com.', '(',
                                             '1463069743',
                                             '1800',
                                             '900',
                                             '604800',
                                             '86400', ')'])]),
                      OrderedDict([('origin', 'com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'ns'),
                                   ('data', ['A.GTLD-SERVERS.NET.'])]),
                      OrderedDict([('origin', 'ns2.muscleextremexxl.com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'a'),
                                   ('data', ['149.255.57.124'])]),
                      OrderedDict([('origin', 'ns3.muscleextremexxl.com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'a'),
                                   ('data', ['193.105.134.6'])]),
                      OrderedDict([('origin', 'ns1.muscleextremexxl.com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'a'),
                                   ('data', ['31.220.42.157'])]),
                      OrderedDict([('origin', 'ns1.newpointnet.com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'a'),
                                   ('data', ['208.67.44.155'])]),
                      OrderedDict([('origin', 'ns2.newpointnet.com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'a'),
                                   ('data', ['198.175.28.6'])]),
                      OrderedDict([('origin', 'ns0.world-of-digital.com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'a'),
                                   ('data', ['212.227.82.151'])]),
                      OrderedDict([('origin', 'ns.hemendemo.com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'a'),
                                   ('data', ['185.87.121.219'])]),
                      OrderedDict([('origin', 'www.poldega.com.'),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'a'),
                                   ('data', ['89.16.164.137'])]),
                      OrderedDict([('origin',
                                    'vrsn-end-of-zone-marker-dummy-record.com.'
                                    ),
                                   ('ttl', '172800'),
                                   ('class', 'in'),
                                   ('type', 'txt'),
                                   ('data', ['plenus'])])]

RFC1035_EXAMPLE = [OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'soa'),
                                ('data',
                                ['VENERA', 'Action\\.domains',
                                 '(', '20', '7200', '600', '3600000',
                                 '60)'])]),
                   OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'ns'),
                                ('data', ['A.ISI.EDU.'])]),
                   OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'ns'),
                                ('data', ['VENERA'])]),
                   OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'ns'),
                                ('data', ['VAXA'])]),
                   OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'mx'),
                                ('data', ['10', 'VENERA'])]),
                   OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'mx'),
                                ('data', ['20', 'VAXA'])]),
                   OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'a'),
                                ('data', ['A', '26.3.0.103'])]),
                   OrderedDict([('origin', 'venera.isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'a'),
                                ('data', ['10.1.0.52'])]),
                   OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'a'),
                                ('data', ['128.9.0.32'])]),
                   OrderedDict([('origin', 'vaxa.isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'a'),
                                ('data', ['10.2.0.27'])]),
                   OrderedDict([('origin', 'isi.edu.'),
                                ('ttl', '900'),
                                ('class', 'in'),
                                ('type', 'a'),
                                ('data', ['128.9.0.33'])])]

# The first 9 lines expected from parsing rfc4035.zone
RFC4035_EXAMPLE = [OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'SOA'),
                                ('data',
                                    ['ns1.example.',
                                     'bugs.x.w.example.', '(',
                                     '1081539377', '3600', '300', '3600000',
                                     '3600', ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'rrsig'),
                                ('data',
                                ['SOA', '5', '1', '3600',
                                 '20040509183619',
                                 '(', '20040409183619',
                                 '38519', 'example.',
                                 'ONx0k36rcjaxYtcNgq6iQnpNV5+drqYAsC9h',
                                 '7TSJaHCqbhE67Sr6aH2xDUGcqQWu/n0UVzrF',
                                 'vkgO9ebarZ0GWDKcuwlM6eNB5SiX2K74l5LW',
                                 'DA7S/Un/IbtDq4Ay8NMNLQI7Dw7n4p8/rjkB',
                                 'jV7j86HyQgM5e7+miRAz8V01b0I=',
                                 ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'ns'),
                                ('data', ['ns1.example.'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'ns'),
                                ('data', ['ns2.example.'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'rrsig'),
                                ('data',
                                ['NS', '5', '1', '3600',
                                 '20040509183619',
                                 '(', '20040409183619',
                                 '38519',
                                 'example.',
                                 'gl13F00f2U0R+SWiXXLHwsMY+qStYy5k6zfd',
                                 'EuivWc+wd1fmbNCyql0Tk7lHTX6UOxc8AgNf',
                                 '4ISFve8XqF4q+o9qlnqIzmppU3LiNeKT4FZ8',
                                 'RO5urFOvoMRTbQxW3U0hXWuggE4g3ZpsHv48',
                                 '0HjMeRaZB/FRPGfJPajngcq6Kwg=',
                                 ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'mx'),
                                ('data', ['1', 'xx.example.'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'rrsig'),
                                ('data',
                                ['MX', '5', '1', '3600',
                                 '20040509183619',
                                 '(', '20040409183619',
                                 '38519',
                                 'example.',
                                 'HyDHYVT5KHSZ7HtO/vypumPmSZQrcOP3tzWB',
                                 '2qaKkHVPfau/DgLgS/IKENkYOGL95G4N+NzE',
                                 'VyNU8dcTOckT+ChPcGeVjguQ7a3Ao9Z/ZkUO',
                                 '6gmmUW4b89rz1PUxW4jzUxj66PTwoVtUU/iM',
                                 'W6OISukd1EQt7a0kygkg+PEDxdI=',
                                 ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'nsec'),
                                ('data', ['a.example.',
                                          'NS', 'SOA', 'MX', 'RRSIG',
                                          'NSEC', 'DNSKEY'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'rrsig'),
                                ('data',
                                ['NSEC', '5', '1', '3600',
                                 '20040509183619',
                                 '(', '20040409183619',
                                 '38519', 'example.',
                                 'O0k558jHhyrC97ISHnislm4kLMW48C7U7cBm',
                                 'FTfhke5iVqNRVTB1STLMpgpbDIC9hcryoO0V',
                                 'Z9ME5xPzUEhbvGnHd5sfzgFVeGxr5Nyyq4tW',
                                 'SDBgIBiLQUv1ivy29vhXy7WgR62dPrZ0PWvm',
                                 'jfFJ5arXf4nPxp/kEowGgBRzY/U=',
                                 ')'])])]

RFC5155_EXAMPLE = [OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'SOA'),
                                ('data',
                                ['ns1.example.', 'bugs.x.w.example.', '1',
                                 '3600', '300', '(', '3600000', '3600',
                                 ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'rrsig'),
                                ('data',
                                ['SOA', '7', '1', '3600', '20150420235959',
                                 '20051021000000', '(', '40430', 'example.',
                                 'Hu25UIyNPmvPIVBrldN+9Mlp9Zql39qaUd8i',
                                 'q4ZLlYWfUUbbAS41pG+68z81q1xhkYAcEyHd',
                                 'VI2LmKusbZsT0Q==', ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'ns'),
                                ('data', ['ns1.example.'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'ns'),
                                ('data', ['ns2.example.'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'rrsig'),
                                ('data',
                                ['NS', '7', '1', '3600', '20150420235959',
                                 '20051021000000', '(', '40430', 'example.',
                                 'PVOgtMK1HHeSTau+HwDWC8Ts+6C8qtqd4pQJ',
                                 'qOtdEVgg+MA+ai4fWDEhu3qHJyLcQ9tbD2vv',
                                 'CnMXjtz6SyObxA==', ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'mx'),
                                ('data', ['1', 'xx.example.'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'rrsig'),
                                ('data',
                                ['MX', '7', '1', '3600', '20150420235959',
                                 '20051021000000', '(', '40430', 'example.',
                                 'GgQ1A9xs47k42VPvpL/a1BWUz/6XsnHkjotw',
                                 '9So8MQtZtl2wJBsnOQsaoHrRCrRbyriEl/GZ',
                                 'n9Mto/Kx+wBo+w==', ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'dnskey'),
                                ('data',
                                ['256', '3', '7',
                                 'AwEAAaetidLzsKWUt4swWR8yu0wPHPiUi8LU', '(',
                                 'sAD0QPWU+wzt89epO6tHzkMBVDkC7qphQO2h',
                                 'TY4hHn9npWFRw5BYubE=', ')'])]),
                   OrderedDict([('origin', 'example.'),
                                ('ttl', '3600'),
                                ('class', 'in'),
                                ('type', 'dnskey'),
                                ('data',
                                ['257', '3', '7',
                                 'AwEAAcUlFV1vhmqx6NSOUOq2R/dsR7Xm3upJ', '(',
                                 'j7IommWSpJABVfW8Q0rOvXdM6kzt+TAu92L9',
                                 'AbsUdblMFin8CVF3n4s=', ')'])])]

@pytest.fixture()
def sample_com_tld():
    com_zone = open('tests/data/com.zone', mode='rt')

    def fin():
        com_zone.close()

    return com_zone


@pytest.fixture()
def rfc_examples():
    rfcs = [1035, 4035, 5155]
    zones = {}

    for rfc in rfcs:
        zones[rfc] = open('tests/data/rfc{}.zone'.format(rfc), mode='rt')

    def fin():
        for rfc in rfcs:
            zones[rfc].close()

    return zones


class TestParse:
    def test_comment_split(self):
        simple_test_comment = "; foobar"
        _, comment = split_comments(simple_test_comment)
        assert "foobar" == comment

    def test_rdata_split(self):
        test_comment = "example.com. NS ns1.example.com ; an example NS record"
        rdata, _ = split_comments(test_comment)
        assert "example.com. NS ns1.example.com" == rdata

    @pytest.mark.usefixtures("sample_com_tld")
    def test_com_tld_parse(self, sample_com_tld):
        zone = [l for l in zone_iterator(sample_com_tld)]
        assert REFERENCE_COM_ZONE == zone

    def test_implicit_origin(self):
        implicit_origin_zone = [zone_dict_to_str(REFERENCE_COM_ZONE[0]),
                                zone_dict_to_str(REFERENCE_COM_ZONE[1])]
        zone = [l for l in zone_iterator(implicit_origin_zone)]
        assert REFERENCE_COM_ZONE[0:2] == zone

    @pytest.mark.usefixtures("rfc_examples")
    def test_rfc_examples(self, rfc_examples):
        zone1035 = [l for l in zone_iterator(rfc_examples[1035])]
        zone4035 = [l for l in zone_iterator(rfc_examples[4035])]
        zone5155 = [l for l in zone_iterator(rfc_examples[5155])]
        assert RFC1035_EXAMPLE == zone1035
        assert RFC4035_EXAMPLE == zone4035[0:9]
        assert RFC5155_EXAMPLE == zone5155[0:9]
